//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringAgent.Data.Interfaces.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Reconfigure = true;
            this.ReconfigureCheckTimeout = 10000;
        }
    
        public int Id { get; set; }
        public Nullable<bool> Reconfigure { get; set; }
        public int ReconfigureCheckTimeout { get; set; }
    }
}
