//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringAgent.Data.Interfaces.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WcfServiceInfoCheckResult
    {
        public int Id { get; set; }
        public Nullable<int> CheckStatus { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Message { get; set; }
        public Nullable<int> Attempt { get; set; }
        public int WcfServiceInfoId { get; set; }
    }
}
