






	SET IDENTITY_INSERT [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ON;
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 52 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(52, 'ASPRO' ,'InsNextSpInterval', 'Produktklasse-SP-Intervall' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,52 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-SP-Intervall'
		WHERE ID = 52
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 53 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(53, 'ASPRO' ,'InsObdStatus', 'Produktklasse-AU-OBD-Status' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,53 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-AU-OBD-Status'
		WHERE ID = 53
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 54 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(54, 'ASPRO' ,'InsOpticalDefect', 'Produktklasse-optische Mängel' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,54 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-optische Mängel'
		WHERE ID = 54
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 59 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(59, 'ASPRO' ,'InsProductClassGroup', 'Produktklasse-Produktklassengruppe' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,59 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-Produktklassengruppe'
		WHERE ID = 59
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 65 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(65, 'ASPRO' ,'InsSeverityType', 'Produktklasse-Mangelbewertungen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,65 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-Mangelbewertungen'
		WHERE ID = 65
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 117 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(117, 'ASPRO' ,'SysLanguage', 'Sprache' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,117 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Sprache'
		WHERE ID = 117
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 72 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(72, 'ASPRO' ,'InsValidPeriod', 'Produktklasse-Zeiträume' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,72 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-Zeiträume'
		WHERE ID = 72
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 47 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(47, 'ASPRO' ,'InsCoreDataProduct', 'Produkt' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,47 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt'
		WHERE ID = 47
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 57 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(57, 'ASPRO' ,'InsPfpPosition', 'Produktklasse-PFP-Prüfpositionen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,57 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-PFP-Prüfpositionen'
		WHERE ID = 57
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 56 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(56, 'ASPRO' ,'InsPfpInspectionTypePfpPositionRsp', 'Zuordnung PFP-Prüfpositionen zu PFP-Baugruppe' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,56 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung PFP-Prüfpositionen zu PFP-Baugruppe'
		WHERE ID = 56
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 49 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(49, 'ASPRO' ,'InsCoreDataProductLocalization', 'Lokalisierung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,49 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Lokalisierung'
		WHERE ID = 49
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 58 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(58, 'ASPRO' ,'InsPfpVehicleType', 'Produktklasse-PFP-Fahrzeugtypen (Silhouetten)' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,58 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-PFP-Fahrzeugtypen (Silhouetten)'
		WHERE ID = 58
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 36 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(36, 'ASPRO' ,'EmpEmployee', 'Mitarbeiter' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,36 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Mitarbeiter'
		WHERE ID = 36
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 71 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(71, 'ASPRO' ,'InsUnitCode', 'berichtende Stellen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,71 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'berichtende Stellen'
		WHERE ID = 71
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 118 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(118, 'ASPRO' ,'SysLocation', 'Standortcode' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,118 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Standortcode'
		WHERE ID = 118
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 120 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(120, 'ASPRO' ,'SysRole', 'Systemrolle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,120 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Systemrolle'
		WHERE ID = 120
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 35 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(35, 'ASPRO' ,'EmpCashPermissionType', 'Auszahlungsrecht' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,35 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Auszahlungsrecht'
		WHERE ID = 35
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 121 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(121, 'ASPRO' ,'SysRoleSysPermissionRsp', 'Zuordnung Rechte zu einer Rolle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,121 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung Rechte zu einer Rolle'
		WHERE ID = 121
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 42 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(42, 'ASPRO' ,'EmpOrgAssociationType', 'Zuordnungsarten zwischen Mitarbeiter und OE' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,42 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnungsarten zwischen Mitarbeiter und OE'
		WHERE ID = 42
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 104 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(104, 'ASPRO' ,'OrgAccountType', 'Abrechnungsvariante' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,104 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Abrechnungsvariante'
		WHERE ID = 104
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 45 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(45, 'ASPRO' ,'InsAvailableInspectionText', 'Systemtext' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,45 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Systemtext'
		WHERE ID = 45
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 105 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(105, 'ASPRO' ,'OrgAccountingArea', 'Buchungskreis' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,105 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Buchungskreis'
		WHERE ID = 105
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 46 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(46, 'ASPRO' ,'InsAvailableInspectionTextValue', 'Zuordnung sptrachabhängiger Systemtexte zu einem Systemtext' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,46 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung sptrachabhängiger Systemtexte zu einem Systemtext'
		WHERE ID = 46
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 106 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(106, 'ASPRO' ,'OrgBankInformation', 'Bankverbindung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,106 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Bankverbindung'
		WHERE ID = 106
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 107 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(107, 'ASPRO' ,'OrgCostCenter', 'Kostenstelle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,107 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kostenstelle'
		WHERE ID = 107
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 96 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(96, 'ASPRO' ,'OrdFederalGroup', 'Bundeslandgruppe' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,96 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Bundeslandgruppe'
		WHERE ID = 96
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 109 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(109, 'ASPRO' ,'OrgCostCenterResponsibleEmployeeRsp', 'Kostenstellenverantwortlicher ' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,109 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kostenstellenverantwortlicher '
		WHERE ID = 109
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 97 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(97, 'ASPRO' ,'OrdFederalState', 'Bundesland' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,97 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Bundesland'
		WHERE ID = 97
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 108 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(108, 'ASPRO' ,'OrgCostCenterPrice', 'Zuordnung Preise zu Kostenstelle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,108 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung Preise zu Kostenstelle'
		WHERE ID = 108
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 116 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(116, 'ASPRO' ,'SysCountry', 'Land ' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,116 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Land '
		WHERE ID = 116
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 119 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(119, 'ASPRO' ,'SysPostCode', 'Postleitzahl' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,119 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Postleitzahl'
		WHERE ID = 119
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 99 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(99, 'ASPRO' ,'OrdOrderCancelationReason', 'Stornogrund' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,99 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Stornogrund'
		WHERE ID = 99
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 113 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(113, 'ASPRO' ,'OrgRelationshipType', 'Hierarchietyp' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,113 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Hierarchietyp'
		WHERE ID = 113
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 74 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(74, 'ASPRO' ,'KssExpenseGround', 'Auszahlungsgrund' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,74 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Auszahlungsgrund'
		WHERE ID = 74
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 110 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(110, 'ASPRO' ,'OrgInformation', 'OE-Information' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,110 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'OE-Information'
		WHERE ID = 110
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 43 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(43, 'ASPRO' ,'ExpPassengersType', 'Mitfahrerart' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,43 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Mitfahrerart'
		WHERE ID = 43
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 114 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(114, 'ASPRO' ,'OrgType', 'OE-Type' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,114 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'OE-Type'
		WHERE ID = 114
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 73 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(73, 'ASPRO' ,'InsVatType', 'Mehrwertsteuersatz' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,73 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Mehrwertsteuersatz'
		WHERE ID = 73
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 111 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(111, 'ASPRO' ,'OrgInspectionDevice', 'OE-Prüfmittel' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,111 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'OE-Prüfmittel'
		WHERE ID = 111
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 37 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(37, 'ASPRO' ,'EmpEmployeeOrgCostCenterRsp', 'Kostenstelle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,37 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kostenstelle'
		WHERE ID = 37
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 93 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(93, 'ASPRO' ,'OrdBillingParameter', 'Kunde-Rechnungsintervalle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,93 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kunde-Rechnungsintervalle'
		WHERE ID = 93
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 38 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(38, 'ASPRO' ,'EmpEmployeeOrgOrganizationalUnitRsp', 'OE/TSC' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,38 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'OE/TSC'
		WHERE ID = 38
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 94 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(94, 'ASPRO' ,'OrdContactPersonFunction', 'Kunde-Funktionen Ansprechpartner' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,94 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kunde-Funktionen Ansprechpartner'
		WHERE ID = 94
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 40 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(40, 'ASPRO' ,'EmpEmployeeTopEmployeeRsp', 'Vorgesetzter' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,40 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Vorgesetzter'
		WHERE ID = 40
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 95 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(95, 'ASPRO' ,'OrdCustomerInfo', 'Kunde-Informationstyp' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,95 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kunde-Informationstyp'
		WHERE ID = 95
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 39 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(39, 'ASPRO' ,'EmpEmployeeSysRoleRsp', 'Rolle' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,39 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Rolle'
		WHERE ID = 39
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 100 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(100, 'ASPRO' ,'OrdPartnerRole', 'Kunde-Partnerrollen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,100 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kunde-Partnerrollen'
		WHERE ID = 100
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 68 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(68, 'ASPRO' ,'InsTaxClass', 'Kunde-Steuerklasse' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,68 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Kunde-Steuerklasse'
		WHERE ID = 68
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 48 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(48, 'ASPRO' ,'InsCoreDataProductGroup', 'Produkt-Arbeitswerte' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,48 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Arbeitswerte'
		WHERE ID = 48
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 60 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(60, 'ASPRO' ,'InsProductCombinationType', 'Produkt-Kombinationstypen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,60 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Kombinationstypen'
		WHERE ID = 60
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 61 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(61, 'ASPRO' ,'InsProductMaterialGroup', 'Produkt-Materialgruppen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,61 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Materialgruppen'
		WHERE ID = 61
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 62 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(62, 'ASPRO' ,'InsProductObjectClass', 'Produkt-Gewichtsklassen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,62 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Gewichtsklassen'
		WHERE ID = 62
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 63 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(63, 'ASPRO' ,'InsProductObjectType', 'Produkt-Objekttypen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,63 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Objekttypen'
		WHERE ID = 63
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 112 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(112, 'ASPRO' ,'OrgOrganizationalUnit', 'Organisationseinheit' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,112 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Organisationseinheit'
		WHERE ID = 112
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 64 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(64, 'ASPRO' ,'InsProductType', 'Produkt-Produkttypen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,64 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Produkttypen'
		WHERE ID = 64
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 66 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(66, 'ASPRO' ,'InsStatisticGroup', 'Produkt-Statistikgruppe' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,66 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Statistikgruppe'
		WHERE ID = 66
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 92 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(92, 'ASPRO' ,'OrdAreaOfWork', 'Produkt-Arbeitsgebiet' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,92 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Arbeitsgebiet'
		WHERE ID = 92
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 103 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(103, 'ASPRO' ,'OrdRecognitionType', 'Produkt-Anerkennungstyp' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,103 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Anerkennungstyp'
		WHERE ID = 103
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 101 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(101, 'ASPRO' ,'OrdRecognition', 'Anerkennung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,101 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Anerkennung'
		WHERE ID = 101
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 102 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(102, 'ASPRO' ,'OrdRecognitionAreaOfWorkRsp', 'Zuordnung Arbeitsgebiet zu Anerkennung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,102 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung Arbeitsgebiet zu Anerkennung'
		WHERE ID = 102
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 69 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(69, 'ASPRO' ,'InsTaxCode', 'Produkt-Steuercode' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,69 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produkt-Steuercode'
		WHERE ID = 69
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 50 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(50, 'ASPRO' ,'InsInspectionStep', 'Produktklasse-Prüfschritt' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,50 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-Prüfschritt'
		WHERE ID = 50
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 44 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(44, 'ASPRO' ,'InsAvailableInspectionStep', 'Zuordnung Verfügbarer Prüfschritt zu Prüfschritt' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,44 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung Verfügbarer Prüfschritt zu Prüfschritt'
		WHERE ID = 44
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 67 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(67, 'ASPRO' ,'InsSummaryField', 'Produktklasse-Ergebnisfeld' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,67 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-Ergebnisfeld'
		WHERE ID = 67
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 51 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(51, 'ASPRO' ,'InsNextInspection', 'Produktklasse-Nächste Prüfung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,51 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END;
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Produktklasse-Nächste Prüfung'
		WHERE ID = 51
	END
	SET IDENTITY_INSERT [SettingsData].[dbo].[MASTER_DATA_PERMISSION] OFF;