






	SET IDENTITY_INSERT [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ON;
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 32 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(32, 'DRL' ,'MessageLocalization', 'Fehlermeldung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,32 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Fehlermeldung'
		WHERE ID = 32
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 6 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(6, 'DRL' ,'CoreDataProduct', 'FE-Produkt' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,6 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'FE-Produkt'
		WHERE ID = 6
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 33 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(33, 'DRL' ,'ReturnReason', 'Rückgabegrund' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,33 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Rückgabegrund'
		WHERE ID = 33
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 20 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(20, 'DRL' ,'ExamPossibleResult', 'Prüfleistungsergebnis' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,20 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Prüfleistungsergebnis'
		WHERE ID = 20
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 34 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(34, 'DRL' ,'SchoolInfo', 'Fahrschulinformationstyp' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,34 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Fahrschulinformationstyp'
		WHERE ID = 34
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 2 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(2, 'DRL' ,'ArgeVersion', 'ARGE-Version' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,2 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'ARGE-Version'
		WHERE ID = 2
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 3 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(3, 'DRL' ,'Authority', 'Behörde' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,3 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Behörde'
		WHERE ID = 3
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 4 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(4, 'DRL' ,'Community', 'Fahrschulgemeinschaft' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,4 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Fahrschulgemeinschaft'
		WHERE ID = 4
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 21 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(21, 'DRL' ,'ExamRecognitionType', 'FE-Anerkennung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,21 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'FE-Anerkennung'
		WHERE ID = 21
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 7 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(7, 'DRL' ,'CoreDataProductClassBasis', 'Rechtsgrund/Klasse' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,7 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Rechtsgrund/Klasse'
		WHERE ID = 7
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 5 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(5, 'DRL' ,'CommunityParticipant', 'Mitglied der Fahrschulgemeinschaft' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,5 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Mitglied der Fahrschulgemeinschaft'
		WHERE ID = 5
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 22 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(22, 'DRL' ,'ExamRecognitionTypeExamClass', 'Zuordnung FE-Klasse zu einer Anerkennung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,22 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung FE-Klasse zu einer Anerkennung'
		WHERE ID = 22
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 9 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(9, 'DRL' ,'DriverSchool', 'Fahrschule' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,9 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Fahrschule'
		WHERE ID = 9
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 23 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(23, 'DRL' ,'ExamRoom', 'Prüfraum' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,23 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Prüfraum'
		WHERE ID = 23
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 24 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(24, 'DRL' ,'ExamStation', 'FE-Prüfort' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,24 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'FE-Prüfort'
		WHERE ID = 24
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 10 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(10, 'DRL' ,'DriverSchoolExamRecognitionType', 'Anerkennung der Fahrschule' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,10 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Anerkennung der Fahrschule'
		WHERE ID = 10
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 11 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(11, 'DRL' ,'DriverSchoolInfo', 'Fahrschule Information' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,11 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Fahrschule Information'
		WHERE ID = 11
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 25 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(25, 'DRL' ,'ExamStationExamRecognitionType', 'Zuordnung FE-Anerkennung zu einem FE-Prüfort' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,25 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung FE-Anerkennung zu einem FE-Prüfort'
		WHERE ID = 25
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 26 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(26, 'DRL' ,'Holiday', 'Feiertag' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,26 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Feiertag'
		WHERE ID = 26
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 12 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(12, 'DRL' ,'ExamClass', 'Klasse' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,12 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Klasse'
		WHERE ID = 12
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 27 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(27, 'DRL' ,'HolidayOrdFederalState', 'Zuordnung Bundesland zu einem Feiertag' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,27 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung Bundesland zu einem Feiertag'
		WHERE ID = 27
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 28 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(28, 'DRL' ,'Language', 'FE-Sprache' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,28 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'FE-Sprache'
		WHERE ID = 28
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 13 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(13, 'DRL' ,'ExamClassArgeMap', 'ARGE-Klassenbezeichnung ' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,13 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'ARGE-Klassenbezeichnung '
		WHERE ID = 13
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 29 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(29, 'DRL' ,'LegalBasis', 'Rechtsgrund' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,29 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Rechtsgrund'
		WHERE ID = 29
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 14 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(14, 'DRL' ,'ExamClassInclusiveClass', 'Inklusivklasse ' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,14 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Inklusivklasse '
		WHERE ID = 14
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 15 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(15, 'DRL' ,'ExamClassMap', 'Zuordnung Alt-Klasse zu einer FE-Klasse' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,15 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung Alt-Klasse zu einer FE-Klasse'
		WHERE ID = 15
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 16 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(16, 'DRL' ,'ExamClassRequiredClass', 'Voraussetzungsklasse ' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,16 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Voraussetzungsklasse '
		WHERE ID = 16
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 8 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(8, 'DRL' ,'CoreDataProductLocalization', 'Lokalisierung' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,8 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Lokalisierung'
		WHERE ID = 8
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 17 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(17, 'DRL' ,'ExamClassRestrictedClass', 'Ausschlussklasse ' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,17 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Ausschlussklasse '
		WHERE ID = 17
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 18 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(18, 'DRL' ,'ExamConstraint', 'Auflagen/Beschränkungen' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,18 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Auflagen/Beschränkungen'
		WHERE ID = 18
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 30 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(30, 'DRL' ,'MeetingPoint', 'Treffpunkt' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,30 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Treffpunkt'
		WHERE ID = 30
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 19 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(19, 'DRL' ,'ExamConstraintExamClass', 'Zuordnung FE-Klasse zu einer FE-Auflage' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,19 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung FE-Klasse zu einer FE-Auflage'
		WHERE ID = 19
	END
	
	IF NOT EXISTS (SELECT ID FROM [SettingsData].[dbo].[MASTER_DATA_PERMISSION] WHERE ID = 31 )
	BEGIN
		INSERT INTO [SettingsData].[dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [DESCRIPTION], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
		VALUES(31, 'DRL' ,'MeetingPointOrganizationalUnit', 'Zuordnung FE-Treffpunkt zu einer Organisationseinheit' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, 1, GETDATE()));
		INSERT INTO [SettingsData].dbo.MASTER_DATA_ROLE_PERMISSION_RSP(MASTER_DATA_ROLE_ID ,MASTER_DATA_PERMISSION_ID ,CREATE_DATE ,CHANGE_DATE ,FROM_DATE ,TO_DATE) 
		VALUES (1 ,31 ,getdate() ,getdate() ,getdate() ,DATEADD(year, 1, GETDATE()));
	END
	ELSE
	BEGIN
		UPDATE [SettingsData].[dbo].[MASTER_DATA_PERMISSION]
		SET [DESCRIPTION] = 'Zuordnung FE-Treffpunkt zu einer Organisationseinheit'
		WHERE ID = 31
	END
	SET IDENTITY_INSERT [SettingsData].[dbo].[MASTER_DATA_PERMISSION] OFF;