






	INSERT INTO [dbo].[MASTER_DATA_PERMISSION] ([ID], [SYSTEM_NAME], [NAME], [CREATE_DATE], [CHANGE_DATE], [DELETE_DATE], [OWNER_ORG_ID], [VISIBILITY_ORG_ID], [CREATE_EMPLOYEE_ID], [CHANGE_EMPLOYEE_ID], [SOURCE], [FROM_DATE], [TO_DATE])
	VALUES
(2000, 'DRL' ,'MessageLocalization' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2001, 'DRL' ,'CoreDataProduct' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2002, 'DRL' ,'ReturnReason' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2003, 'DRL' ,'ExamPossibleResult' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2004, 'DRL' ,'SchoolInfo' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2005, 'DRL' ,'ArgeVersion' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2006, 'DRL' ,'Authority' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2007, 'DRL' ,'Community' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2008, 'DRL' ,'ExamRecognitionType' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2009, 'DRL' ,'CoreDataProductClassBasis' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2010, 'DRL' ,'CommunityParticipant' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2011, 'DRL' ,'ExamRecognitionTypeExamClass' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2012, 'DRL' ,'DriverSchool' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2013, 'DRL' ,'ExamRoom' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2014, 'DRL' ,'ExamStation' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2015, 'DRL' ,'DriverSchoolExamRecognitionType' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2016, 'DRL' ,'DriverSchoolInfo' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2017, 'DRL' ,'ExamStationExamRecognitionType' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2018, 'DRL' ,'Holiday' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2019, 'DRL' ,'ExamClass' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2020, 'DRL' ,'HolidayOrdFederalState' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2021, 'DRL' ,'Language' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2022, 'DRL' ,'ExamClassArgeMap' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2023, 'DRL' ,'LegalBasis' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2024, 'DRL' ,'ExamClassInclusiveClass' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2025, 'DRL' ,'ExamClassMap' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2026, 'DRL' ,'ExamClassRequiredClass' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2027, 'DRL' ,'CoreDataProductLocalization' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2028, 'DRL' ,'ExamClassRestrictedClass' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2029, 'DRL' ,'ExamConstraint' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2030, 'DRL' ,'MeetingPoint' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2031, 'DRL' ,'ExamConstraintExamClass' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
,(2032, 'DRL' ,'MeetingPointOrganizationalUnit' ,GETDATE() ,GETDATE() ,NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), DATEADD(year, -1, GETDATE()))
