//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;    
using System.Data.Entity.ModelConfiguration;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.Common;
namespace TuevSued.V1.IT.FE.MasterDataModule.Lib.Data
{
        /// <summary>
        /// Database mapping for <see cref="InsCoreDataProductLocalization"/> to table INS_CORE_DATA_PRODUCT_LOCALIZATION
        /// </summary>
        internal sealed class InsCoreDataProductLocalizationMapping : EntityTypeConfiguration<InsCoreDataProductLocalization>
        {
    	    public static readonly InsCoreDataProductLocalizationMapping Instance = new InsCoreDataProductLocalizationMapping();
    	    /// <summary>
            /// Instance constructor
            /// </summary>
            private InsCoreDataProductLocalizationMapping()
            {
                // Primary Key
                this.HasKey(t => t.Id);
    
                // Properties
                this.Property(t => t.Id)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.ProductName)
                    .IsRequired()
                    .IsUnicode()
                    .HasMaxLength(250);
    
                this.Property(t => t.Description)
                    .IsUnicode()
                    .HasMaxLength(250);
    
                this.Property(t => t.CreateDate)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.Source)
                    .HasMaxLength(4);
    
                // Table & Column Mappings
                this.ToTable("INS_CORE_DATA_PRODUCT_LOCALIZATION", "DBO");
                this.Property(t => t.Id).HasColumnName(InsCoreDataProductLocalization.Fields.Id);
                this.Property(t => t.InsCoreDataProductId).HasColumnName(InsCoreDataProductLocalization.Fields.InsCoreDataProductId);
                this.Property(t => t.SysLanguageId).HasColumnName(InsCoreDataProductLocalization.Fields.SysLanguageId);
                this.Property(t => t.ProductName).HasColumnName(InsCoreDataProductLocalization.Fields.ProductName);
                this.Property(t => t.Description).HasColumnName(InsCoreDataProductLocalization.Fields.Description);
                this.Property(t => t.CreateDate).HasColumnName(InsCoreDataProductLocalization.Fields.CreateDate);
                this.Property(t => t.ChangeDate).HasColumnName(InsCoreDataProductLocalization.Fields.ChangeDate);
                this.Property(t => t.DeleteDate).HasColumnName(InsCoreDataProductLocalization.Fields.DeleteDate);
                this.Property(t => t.OwnerOrgId).HasColumnName(InsCoreDataProductLocalization.Fields.OwnerOrgId);
                this.Property(t => t.VisibilityOrgId).HasColumnName(InsCoreDataProductLocalization.Fields.VisibilityOrgId);
                this.Property(t => t.CreateEmployeeId).HasColumnName(InsCoreDataProductLocalization.Fields.CreateEmployeeId);
                this.Property(t => t.ChangeEmployeeId).HasColumnName(InsCoreDataProductLocalization.Fields.ChangeEmployeeId);
                this.Property(t => t.Source).HasColumnName(InsCoreDataProductLocalization.Fields.Source);
                this.Property(t => t.FromDate).HasColumnName(InsCoreDataProductLocalization.Fields.FromDate);
                this.Property(t => t.ToDate).HasColumnName(InsCoreDataProductLocalization.Fields.ToDate);
    
    
            }
        }
}
