//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;    
using System.Data.Entity.ModelConfiguration;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.Common;
namespace TuevSued.V1.IT.FE.MasterDataModule.Lib.Data
{
        /// <summary>
        /// Database mapping for <see cref="SysLanguage"/> to table SYS_LANGUAGE
        /// </summary>
        internal sealed class SysLanguageMapping : EntityTypeConfiguration<SysLanguage>
        {
    	    public static readonly SysLanguageMapping Instance = new SysLanguageMapping();
    	    /// <summary>
            /// Instance constructor
            /// </summary>
            private SysLanguageMapping()
            {
                // Primary Key
                this.HasKey(t => t.Id);
    
                // Properties
                this.Property(t => t.Id)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.SapId)
                    .IsRequired()
                    .IsFixedLength()
                    .HasMaxLength(10);
    
                this.Property(t => t.SapIdIso)
                    .HasMaxLength(10);
    
                this.Property(t => t.ResourceFileName)
                    .IsUnicode()
                    .HasMaxLength(10);
    
                this.Property(t => t.Description)
                    .IsUnicode()
                    .HasMaxLength(50);
    
                this.Property(t => t.CreateDate)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.Source)
                    .HasMaxLength(4);
    
                // Table & Column Mappings
                this.ToTable("SYS_LANGUAGE", "DBO");
                this.Property(t => t.Id).HasColumnName(SysLanguage.Fields.Id);
                this.Property(t => t.SapId).HasColumnName(SysLanguage.Fields.SapId);
                this.Property(t => t.SapIdIso).HasColumnName(SysLanguage.Fields.SapIdIso);
                this.Property(t => t.ResourceFileName).HasColumnName(SysLanguage.Fields.ResourceFileName);
                this.Property(t => t.IsAvailable).HasColumnName(SysLanguage.Fields.IsAvailable);
                this.Property(t => t.Description).HasColumnName(SysLanguage.Fields.Description);
                this.Property(t => t.CreateDate).HasColumnName(SysLanguage.Fields.CreateDate);
                this.Property(t => t.ChangeDate).HasColumnName(SysLanguage.Fields.ChangeDate);
                this.Property(t => t.DeleteDate).HasColumnName(SysLanguage.Fields.DeleteDate);
                this.Property(t => t.OwnerOrgId).HasColumnName(SysLanguage.Fields.OwnerOrgId);
                this.Property(t => t.VisibilityOrgId).HasColumnName(SysLanguage.Fields.VisibilityOrgId);
                this.Property(t => t.CreateEmployeeId).HasColumnName(SysLanguage.Fields.CreateEmployeeId);
                this.Property(t => t.ChangeEmployeeId).HasColumnName(SysLanguage.Fields.ChangeEmployeeId);
                this.Property(t => t.Source).HasColumnName(SysLanguage.Fields.Source);
            }
        }
}
