//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.DriverLicenceMasterData;

namespace TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.Common
{
    /// <summary>
    /// Entity from table INS_CORE_DATA_PRODUCT. Imported from AsPro: Dictionary data. Includes all products which can be used in AS1313 application  
    /// </summary>
    public partial class InsCoreDataProduct : IHasId<int>, ICommonSystemFields, ISystemFields, IRemovable, IHasTitle
    {
    
        /// <summary>
        /// Table name
        /// </summary>
        public static readonly string EntityTableName = "INS_CORE_DATA_PRODUCT";
        #region Fields
        /// <summary>
        /// Columns names
        /// </summary>
        public static class Fields
        {
            /// <summary>
            /// Column name 'ID' for property <see cref="InsCoreDataProduct.Id"/>
            /// </summary>
            public static readonly string Id = "ID";
            /// <summary>
            /// Column name 'PRODUCT_NUMBER' for property <see cref="InsCoreDataProduct.ProductNumber"/>
            /// </summary>
            public static readonly string ProductNumber = "PRODUCT_NUMBER";
            /// <summary>
            /// Column name 'IS_NEXT_INSPECTION_PRODUCT' for property <see cref="InsCoreDataProduct.IsNextInspectionProduct"/>
            /// </summary>
            public static readonly string IsNextInspectionProduct = "IS_NEXT_INSPECTION_PRODUCT";
            /// <summary>
            /// Column name 'IS_PROVISION_COST_MAY_BE_CALCULATED' for property <see cref="InsCoreDataProduct.IsProvisionCostMayBeCalculated"/>
            /// </summary>
            public static readonly string IsProvisionCostMayBeCalculated = "IS_PROVISION_COST_MAY_BE_CALCULATED";
            /// <summary>
            /// Column name 'PRICE_REPORT_REQUIRED' for property <see cref="InsCoreDataProduct.PriceReportRequired"/>
            /// </summary>
            public static readonly string PriceReportRequired = "PRICE_REPORT_REQUIRED";
            /// <summary>
            /// Column name 'INS_PRODUCT_TYPE_ID' for property <see cref="InsCoreDataProduct.InsProductTypeId"/>
            /// </summary>
            public static readonly string InsProductTypeId = "INS_PRODUCT_TYPE_ID";
            /// <summary>
            /// Column name 'INS_PRODUCT_OBJECT_CLASS_ID' for property <see cref="InsCoreDataProduct.InsProductObjectClassId"/>
            /// </summary>
            public static readonly string InsProductObjectClassId = "INS_PRODUCT_OBJECT_CLASS_ID";
            /// <summary>
            /// Column name 'INS_PRODUCT_OBJECT_TYPE_ID' for property <see cref="InsCoreDataProduct.InsProductObjectTypeId"/>
            /// </summary>
            public static readonly string InsProductObjectTypeId = "INS_PRODUCT_OBJECT_TYPE_ID";
            /// <summary>
            /// Column name 'INS_PRODUCT_MATERIAL_GROUP_ID' for property <see cref="InsCoreDataProduct.InsProductMaterialGroupId"/>
            /// </summary>
            public static readonly string InsProductMaterialGroupId = "INS_PRODUCT_MATERIAL_GROUP_ID";
            /// <summary>
            /// Column name 'INS_PRODUCT_CLASS_ID' for property <see cref="InsCoreDataProduct.InsProductClassId"/>
            /// </summary>
            public static readonly string InsProductClassId = "INS_PRODUCT_CLASS_ID";
            /// <summary>
            /// Column name 'INS_CORE_DATA_PRODUCT_GROUP_ID' for property <see cref="InsCoreDataProduct.InsCoreDataProductGroupId"/>
            /// </summary>
            public static readonly string InsCoreDataProductGroupId = "INS_CORE_DATA_PRODUCT_GROUP_ID";
            /// <summary>
            /// Column name 'IS_INGENER' for property <see cref="InsCoreDataProduct.IsIngener"/>
            /// </summary>
            public static readonly string IsIngener = "IS_INGENER";
            /// <summary>
            /// Column name 'IS_PRODUCTIVE' for property <see cref="InsCoreDataProduct.IsProductive"/>
            /// </summary>
            public static readonly string IsProductive = "IS_PRODUCTIVE";
            /// <summary>
            /// Column name 'IS_KM_GELD' for property <see cref="InsCoreDataProduct.IsKmGeld"/>
            /// </summary>
            public static readonly string IsKmGeld = "IS_KM_GELD";
            /// <summary>
            /// Column name 'IS_OTHER_MATERIAL' for property <see cref="InsCoreDataProduct.IsOtherMaterial"/>
            /// </summary>
            public static readonly string IsOtherMaterial = "IS_OTHER_MATERIAL";
            /// <summary>
            /// Column name 'IS_TRIP' for property <see cref="InsCoreDataProduct.IsTrip"/>
            /// </summary>
            public static readonly string IsTrip = "IS_TRIP";
            /// <summary>
            /// Column name 'CREATE_DATE' for property <see cref="InsCoreDataProduct.CreateDate"/>
            /// </summary>
            public static readonly string CreateDate = "CREATE_DATE";
            /// <summary>
            /// Column name 'CHANGE_DATE' for property <see cref="InsCoreDataProduct.ChangeDate"/>
            /// </summary>
            public static readonly string ChangeDate = "CHANGE_DATE";
            /// <summary>
            /// Column name 'DELETE_DATE' for property <see cref="InsCoreDataProduct.DeleteDate"/>
            /// </summary>
            public static readonly string DeleteDate = "DELETE_DATE";
            /// <summary>
            /// Column name 'OWNER_ORG_ID' for property <see cref="InsCoreDataProduct.OwnerOrgId"/>
            /// </summary>
            public static readonly string OwnerOrgId = "OWNER_ORG_ID";
            /// <summary>
            /// Column name 'VISIBILITY_ORG_ID' for property <see cref="InsCoreDataProduct.VisibilityOrgId"/>
            /// </summary>
            public static readonly string VisibilityOrgId = "VISIBILITY_ORG_ID";
            /// <summary>
            /// Column name 'CREATE_EMPLOYEE_ID' for property <see cref="InsCoreDataProduct.CreateEmployeeId"/>
            /// </summary>
            public static readonly string CreateEmployeeId = "CREATE_EMPLOYEE_ID";
            /// <summary>
            /// Column name 'CHANGE_EMPLOYEE_ID' for property <see cref="InsCoreDataProduct.ChangeEmployeeId"/>
            /// </summary>
            public static readonly string ChangeEmployeeId = "CHANGE_EMPLOYEE_ID";
            /// <summary>
            /// Column name 'SOURCE' for property <see cref="InsCoreDataProduct.Source"/>
            /// </summary>
            public static readonly string Source = "SOURCE";
            /// <summary>
            /// Column name 'FROM_DATE' for property <see cref="InsCoreDataProduct.FromDate"/>
            /// </summary>
            public static readonly string FromDate = "FROM_DATE";
            /// <summary>
            /// Column name 'TO_DATE' for property <see cref="InsCoreDataProduct.ToDate"/>
            /// </summary>
            public static readonly string ToDate = "TO_DATE";
            /// <summary>
            /// Column name 'REUSAGE_TYPE' for property <see cref="InsCoreDataProduct.ReusageType"/>
            /// </summary>
            public static readonly string ReusageType = "REUSAGE_TYPE";
            /// <summary>
            /// Column name 'INS_TAX_CODE_ID' for property <see cref="InsCoreDataProduct.InsTaxCodeId"/>
            /// </summary>
            public static readonly string InsTaxCodeId = "INS_TAX_CODE_ID";
            /// <summary>
            /// Column name 'OLD_PRODUCT_NUMBER' for property <see cref="InsCoreDataProduct.OldProductNumber"/>
            /// </summary>
            public static readonly string OldProductNumber = "OLD_PRODUCT_NUMBER";
      
        }
        #endregion
        /// <summary>
        /// Constructor
        /// </summary>
        public InsCoreDataProduct()
        {
            this.CoreDataProducts = new HashSet<CoreDataProduct>();
            this.InsCoreDataProductLocalizations = new HashSet<InsCoreDataProductLocalization>();
        }
    
        /// <summary>
        /// PK  
        /// </summary>
        public int Id {  get;  set; }
        /// <summary>
        /// Unique product number. Original table: INS_CORE_DATA_PRODUCT_2, Column: PRODUCT_NUMBER  
        /// </summary>
        public string ProductNumber {  get;  set; }
        /// <summary>
        /// Indicates whether product capable of verification. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_NEXT_INSPECTION_PRODUCT  
        /// </summary>
        public bool? IsNextInspectionProduct {  get;  set; }
        /// <summary>
        /// Indication of whether benefits for this product are calculated. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_PROVISION_COST_MAY_BE_CALCULATED  
        /// </summary>
        public bool? IsProvisionCostMayBeCalculated {  get;  set; }
        /// <summary>
        /// Represent a value indicating whether price report is required for this product. Original table: INS_CORE_DATA_PRODUCT_2, Column: PRICE_REPORT_REQUIRED  
        /// </summary>
        public bool? PriceReportRequired {  get;  set; }
        /// <summary>
        /// Product Type. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_PRODUCT_TYPE_ID  
        /// </summary>
        public int InsProductTypeId {  get;  set; }
        /// <summary>
        /// Represents object clas associated with this product.. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_PRODUCT_OBJECT_CLASS_ID  
        /// </summary>
        public int? InsProductObjectClassId {  get;  set; }
        /// <summary>
        /// Product object type.. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_PRODUCT_OBJECT_TYPE_ID  
        /// </summary>
        public int? InsProductObjectTypeId {  get;  set; }
        /// <summary>
        /// Product material group.. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_PRODUCT_MATERIAL_GROUP_ID  
        /// </summary>
        public int? InsProductMaterialGroupId {  get;  set; }
        /// <summary>
        /// Foreign key to INS_PRODUCT_CLASS. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_PRODUCT_CLASS_ID  
        /// </summary>
        public int? InsProductClassId {  get;  set; }
        /// <summary>
        /// Core data product group.. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_CORE_DATA_PRODUCT_GROUP_ID  
        /// </summary>
        public int? InsCoreDataProductGroupId {  get;  set; }
        /// <summary>
        /// Engineer product. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_INGENER  
        /// </summary>
        public bool? IsIngener {  get;  set; }
        /// <summary>
        /// Product will be shown in the TP. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_PRODUCTIVE  
        /// </summary>
        public int IsProductive {  get;  set; }
        /// <summary>
        /// KM-Geld product. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_KM_GELD  
        /// </summary>
        public bool IsKmGeld {  get;  set; }
        /// <summary>
        /// "Sonstige" product. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_OTHER_MATERIAL  
        /// </summary>
        public bool IsOtherMaterial {  get;  set; }
        /// <summary>
        /// Indicates if the product is trip.. Original table: INS_CORE_DATA_PRODUCT_2, Column: IS_TRIP  
        /// </summary>
        public bool IsTrip {  get;  set; }
        /// <summary>
        /// Create date. Original table: INS_CORE_DATA_PRODUCT_2, Column: CREATE_DATE  
        /// </summary>
        public System.DateTime? CreateDate {  get;  set; }
        /// <summary>
        /// Change date. Original table: INS_CORE_DATA_PRODUCT_2, Column: CHANGE_DATE  
        /// </summary>
        public System.DateTime? ChangeDate {  get;  set; }
        /// <summary>
        /// Delete date. Original table: INS_CORE_DATA_PRODUCT_2, Column: DELETE_DATE  
        /// </summary>
        public System.DateTime? DeleteDate {  get;  set; }
        /// <summary>
        /// Owner of record concerning organizational hierarchy. Original table: INS_CORE_DATA_PRODUCT_2, Column: OWNER_ORG_ID  
        /// </summary>
        public int? OwnerOrgId {  get;  set; }
        /// <summary>
        /// Visibility of record concerning organizational hierarchy. Original table: INS_CORE_DATA_PRODUCT_2, Column: VISIBILITY_ORG_ID  
        /// </summary>
        public int? VisibilityOrgId {  get;  set; }
        /// <summary>
        /// Employee who created record. Original table: INS_CORE_DATA_PRODUCT_2, Column: CREATE_EMPLOYEE_ID  
        /// </summary>
        public int? CreateEmployeeId {  get;  set; }
        /// <summary>
        /// Employee who changed record. Original table: INS_CORE_DATA_PRODUCT_2, Column: CHANGE_EMPLOYEE_ID  
        /// </summary>
        public int? ChangeEmployeeId {  get;  set; }
        /// <summary>
        /// Short name of source data. Original table: INS_CORE_DATA_PRODUCT_2, Column: SOURCE  
        /// </summary>
        public string Source {  get;  set; }
        /// <summary>
        /// Validity start date. Original table: INS_CORE_DATA_PRODUCT_2, Column: FROM_DATE  
        /// </summary>
        public System.DateTime FromDate {  get;  set; }
        /// <summary>
        /// Validity end date. Original table: INS_CORE_DATA_PRODUCT_2, Column: TO_DATE  
        /// </summary>
        public System.DateTime ToDate {  get;  set; }
        /// <summary>
        /// Indicates how many times the product can be used in order.. Original table: INS_CORE_DATA_PRODUCT_2, Column: REUSAGE_TYPE  
        /// </summary>
        public int ReusageType {  get;  set; }
        /// <summary>
        /// Relation to INS_TAX_CODE table. Original table: INS_CORE_DATA_PRODUCT_2, Column: INS_TAX_CODE_ID  
        /// </summary>
        public int? InsTaxCodeId {  get;  set; }
        /// <summary>
        /// Represents product number in the old system. Original table: INS_CORE_DATA_PRODUCT_2, Column: OLD_PRODUCT_NUMBER  
        /// </summary>
        public string OldProductNumber {  get;  set; }
        /// <summary>
        /// Navigation property to object DRL_CORE_DATA_PRODUCT. Comment: EN: 5.3.5.15 Product - assign Additional Details  DE: 5.3.5.15 Produkt - FE-Zusatzdaten zuordnen  
        /// </summary>
        public virtual ICollection<CoreDataProduct> CoreDataProducts {  get;  set; }
    
    	/// <summary>
    	/// Filtered collection of <see cref="CoreDataProducts"/>
    	/// </summary>
    	public IEnumerable<CoreDataProduct> CoreDataProductsFiltered 
    	{
    		get
    		{
    			return CoreDataProducts.Where(SystemFilter<CoreDataProduct>.Func);
    		}
    	}
    			
        /// <summary>
        /// From date entity valid 
        /// </summary>
    	DateTime? ISystemFields.FromDate
    	{
    	    get { 
    		      return FromDate; 
    			}
    		set { 
    		      if(value.HasValue){FromDate = value.Value;} else{ throw new ArgumentNullException("value"); } 
    			}
    	}    
        /// <summary>
        /// To date entity valid 
        /// </summary>
    	DateTime? ISystemFields.ToDate
    	{
    	    get { 
    		      return ToDate; 
    			}
    		set { 
    		      if(value.HasValue){ToDate = value.Value;} else{ throw new ArgumentNullException("value"); } 
    			}
    	}


        /// <summary>
        /// Navigation property to object DRL_CORE_DATA_PRODUCT_LOCALIZATION. Comment: EN: Core data product localization  
        /// </summary>
        public virtual ICollection<InsCoreDataProductLocalization> InsCoreDataProductLocalizations { get; set; }

        /// <summary>
        /// Filtered collection of <see cref="CoreDataProductLocalizations"/>
        /// </summary>
        public IEnumerable<InsCoreDataProductLocalization> InsCoreDataProductLocalizationsFiltered
        {
            get
            {
                return InsCoreDataProductLocalizations.Where(SystemFilter<InsCoreDataProductLocalization>.Func);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string EntityTitle
        {
            get
            {
                //TODO
                var result = "TODO";

                if (InsCoreDataProductLocalizations != null && InsCoreDataProductLocalizations.Count != 0)
                {
                    result = InsCoreDataProductLocalizations.FirstOrDefault().ProductName;
                }

                return result;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string EntityDescription
        {
            get
            {
                //TODO
                var result = "TODO";

                if (InsCoreDataProductLocalizations != null && InsCoreDataProductLocalizations.Count != 0)
                {
                    result = InsCoreDataProductLocalizations.FirstOrDefault().Description;
                }

                return result;
            }
        }

        /// <summary>
        /// Shallow copy of object. Exclude navigation properties and PK properties
        /// </summary>
        public InsCoreDataProduct ShallowCopy()
    	{
    	   return new InsCoreDataProduct {
                                           ProductNumber = this.ProductNumber,
                                           IsNextInspectionProduct = this.IsNextInspectionProduct,
                                           IsProvisionCostMayBeCalculated = this.IsProvisionCostMayBeCalculated,
                                           PriceReportRequired = this.PriceReportRequired,
                                           InsProductTypeId = this.InsProductTypeId,
                                           InsProductObjectClassId = this.InsProductObjectClassId,
                                           InsProductObjectTypeId = this.InsProductObjectTypeId,
                                           InsProductMaterialGroupId = this.InsProductMaterialGroupId,
                                           InsProductClassId = this.InsProductClassId,
                                           InsCoreDataProductGroupId = this.InsCoreDataProductGroupId,
                                           IsIngener = this.IsIngener,
                                           IsProductive = this.IsProductive,
                                           IsKmGeld = this.IsKmGeld,
                                           IsOtherMaterial = this.IsOtherMaterial,
                                           IsTrip = this.IsTrip,
                                           DeleteDate = this.DeleteDate,
                                           Source = this.Source,
                                           ReusageType = this.ReusageType,
                                           InsTaxCodeId = this.InsTaxCodeId,
                                           OldProductNumber = this.OldProductNumber,
    	                              };
    	}
    }
}
