//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.Common
{
    /// <summary>
    /// Entity from table INS_CORE_DATA_PRODUCT_LOCALIZATION. Imported from AsPro: Localized product names  
    /// </summary>
    public partial class InsCoreDataProductLocalization : IHasId<int>, ICommonSystemFields, ISystemFields, IRemovable, IHasTitle
    {
    
        /// <summary>
        /// Table name
        /// </summary>
        public static readonly string EntityTableName = "INS_CORE_DATA_PRODUCT_LOCALIZATION";
        #region Fields
        /// <summary>
        /// Columns names
        /// </summary>
        public static class Fields
        {
            /// <summary>
            /// Column name 'ID' for property <see cref="InsCoreDataProductLocalization.Id"/>
            /// </summary>
            public static readonly string Id = "ID";
            /// <summary>
            /// Column name 'INS_CORE_DATA_PRODUCT_ID' for property <see cref="InsCoreDataProductLocalization.InsCoreDataProductId"/>
            /// </summary>
            public static readonly string InsCoreDataProductId = "INS_CORE_DATA_PRODUCT_ID";
            /// <summary>
            /// Column name 'SYS_LANGUAGE_ID' for property <see cref="InsCoreDataProductLocalization.SysLanguageId"/>
            /// </summary>
            public static readonly string SysLanguageId = "SYS_LANGUAGE_ID";
            /// <summary>
            /// Column name 'PRODUCT_NAME' for property <see cref="InsCoreDataProductLocalization.ProductName"/>
            /// </summary>
            public static readonly string ProductName = "PRODUCT_NAME";
            /// <summary>
            /// Column name 'DESCRIPTION' for property <see cref="InsCoreDataProductLocalization.Description"/>
            /// </summary>
            public static readonly string Description = "DESCRIPTION";
            /// <summary>
            /// Column name 'CREATE_DATE' for property <see cref="InsCoreDataProductLocalization.CreateDate"/>
            /// </summary>
            public static readonly string CreateDate = "CREATE_DATE";
            /// <summary>
            /// Column name 'CHANGE_DATE' for property <see cref="InsCoreDataProductLocalization.ChangeDate"/>
            /// </summary>
            public static readonly string ChangeDate = "CHANGE_DATE";
            /// <summary>
            /// Column name 'DELETE_DATE' for property <see cref="InsCoreDataProductLocalization.DeleteDate"/>
            /// </summary>
            public static readonly string DeleteDate = "DELETE_DATE";
            /// <summary>
            /// Column name 'OWNER_ORG_ID' for property <see cref="InsCoreDataProductLocalization.OwnerOrgId"/>
            /// </summary>
            public static readonly string OwnerOrgId = "OWNER_ORG_ID";
            /// <summary>
            /// Column name 'VISIBILITY_ORG_ID' for property <see cref="InsCoreDataProductLocalization.VisibilityOrgId"/>
            /// </summary>
            public static readonly string VisibilityOrgId = "VISIBILITY_ORG_ID";
            /// <summary>
            /// Column name 'CREATE_EMPLOYEE_ID' for property <see cref="InsCoreDataProductLocalization.CreateEmployeeId"/>
            /// </summary>
            public static readonly string CreateEmployeeId = "CREATE_EMPLOYEE_ID";
            /// <summary>
            /// Column name 'CHANGE_EMPLOYEE_ID' for property <see cref="InsCoreDataProductLocalization.ChangeEmployeeId"/>
            /// </summary>
            public static readonly string ChangeEmployeeId = "CHANGE_EMPLOYEE_ID";
            /// <summary>
            /// Column name 'SOURCE' for property <see cref="InsCoreDataProductLocalization.Source"/>
            /// </summary>
            public static readonly string Source = "SOURCE";
            /// <summary>
            /// Column name 'FROM_DATE' for property <see cref="InsCoreDataProductLocalization.FromDate"/>
            /// </summary>
            public static readonly string FromDate = "FROM_DATE";
            /// <summary>
            /// Column name 'TO_DATE' for property <see cref="InsCoreDataProductLocalization.ToDate"/>
            /// </summary>
            public static readonly string ToDate = "TO_DATE";
      
        }
        #endregion
        /// <summary>
        /// PK. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: ID  
        /// </summary>
        public int Id {  get;  set; }
        /// <summary>
        /// Related product.. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: INS_CORE_DATA_PRODUCT_ID  
        /// </summary>
        public int InsCoreDataProductId {  get;  set; }
        /// <summary>
        /// Language of product name.. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: SYS_LANGUAGE_ID  
        /// </summary>
        public int SysLanguageId {  get;  set; }
        /// <summary>
        /// Localized product name.. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: PRODUCT_NAME  
        /// </summary>
        public string ProductName {  get;  set; }
        /// <summary>
        /// Localized product description. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: DESCRIPTION  
        /// </summary>
        public string Description {  get;  set; }
        /// <summary>
        /// Create date. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: CREATE_DATE  
        /// </summary>
        public System.DateTime? CreateDate {  get;  set; }
        /// <summary>
        /// Change date. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: CHANGE_DATE  
        /// </summary>
        public System.DateTime? ChangeDate {  get;  set; }
        /// <summary>
        /// Delete date. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: DELETE_DATE  
        /// </summary>
        public System.DateTime? DeleteDate {  get;  set; }
        /// <summary>
        /// Owner of record concerning organizational hierarchy. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: OWNER_ORG_ID  
        /// </summary>
        public int? OwnerOrgId {  get;  set; }
        /// <summary>
        /// Visibility of record concerning organizational hierarchy. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: VISIBILITY_ORG_ID  
        /// </summary>
        public int? VisibilityOrgId {  get;  set; }
        /// <summary>
        /// Employee who created record. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: CREATE_EMPLOYEE_ID  
        /// </summary>
        public int? CreateEmployeeId {  get;  set; }
        /// <summary>
        /// Employee who changed record. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: CHANGE_EMPLOYEE_ID  
        /// </summary>
        public int? ChangeEmployeeId {  get;  set; }
        /// <summary>
        /// Short name of source data. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: SOURCE  
        /// </summary>
        public string Source {  get;  set; }
        /// <summary>
        /// Validity start date. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: FROM_DATE  
        /// </summary>
        public System.DateTime FromDate {  get;  set; }
        /// <summary>
        /// Validity end date. Original table: INS_CORE_DATA_PRODUCT_LOCALIZATION, Column: TO_DATE  
        /// </summary>
        public System.DateTime ToDate {  get;  set; }
        /// <summary>
        /// From date entity valid 
        /// </summary>
    	DateTime? ISystemFields.FromDate
    	{
    	    get { 
    		      return FromDate; 
    			}
    		set { 
    		      if(value.HasValue){FromDate = value.Value;} else{ throw new ArgumentNullException("value"); } 
    			}
    	}    
        /// <summary>
        /// To date entity valid 
        /// </summary>
    	DateTime? ISystemFields.ToDate
    	{
    	    get { 
    		      return ToDate; 
    			}
    		set { 
    		      if(value.HasValue){ToDate = value.Value;} else{ throw new ArgumentNullException("value"); } 
    			}
    	}


        /// <summary>
        /// 
        /// </summary>
        public string EntityTitle { get { return ProductName; } }

        /// <summary>
        /// Shallow copy of object. Exclude navigation properties and PK properties
        /// </summary>
        public InsCoreDataProductLocalization ShallowCopy()
    	{
    	   return new InsCoreDataProductLocalization {
                                           InsCoreDataProductId = this.InsCoreDataProductId,
                                           SysLanguageId = this.SysLanguageId,
                                           ProductName = this.ProductName,
                                           Description = this.Description,
                                           DeleteDate = this.DeleteDate,
                                           Source = this.Source,
    	                              };
    	}
    }
}
