//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace TuevSued.V1.IT.CoreBase.Entities.MasterDataModule
{
    /// <summary>
    /// Interface entity with common system fields 
    /// </summary>
    public interface ICommonSystemFields
    {
        /// <summary>
        /// Entity create date 
        /// </summary>
        DateTime? CreateDate { get;set; }

        /// <summary>
        /// Last changed date 
        /// </summary>
        DateTime? ChangeDate { get; set; }
        
        /// <summary>
        /// OWNER (SCHLUESSEL EINER ORGANISATIONSEINHEIT, WELCHE FUER DIE PFLEGE EINES DATENSATZES 
        /// </summary>
        int? OwnerOrgId { get;set; }
        /// <summary>
        /// SICHTBARKEIT (SCHLUESSEL EINER ORGANISATIONSEINHEIT, AB WELCHER IM HIERACHIEBAUM ABWAERTS EIN DATENSATZ SICHTBAR IST) 
        /// </summary>
        int? VisibilityOrgId { get;set; }
        /// <summary>
        /// ANLEGER (PERSONALNUMMER DES MITARBEITERS, DER DEN DATENSATZ ANGELEGT HAT) 
        /// </summary>
        int? CreateEmployeeId { get;set; }
        /// <summary>
        /// AENDERER (PERSONALNUMMER DES MITARBEITERS, DER DEN DATENSATZ ALS LETZTES GEAENDERT HAT, BEI NEUANLAGE IST DIESER WERT GLEICH DEM ANLEGER) 
        /// </summary>
        int? ChangeEmployeeId { get;set; }
    }
}
