//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace TuevSued.V1.IT.CoreBase.Entities.MasterDataModule
{
    /// <summary>
    /// Interface entity with all system fields 
    /// </summary>
    public interface ISystemFields: ICommonSystemFields
    {
        /// <summary>
        /// From date entity valid 
        /// </summary>
        DateTime? FromDate { get;set; }
        /// <summary>
        /// To date entity valid 
        /// </summary>
        DateTime? ToDate { get;set; }
    }
}
