//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Practices.Unity;
using MonitoringAgent.Common.Data.Managers;
using MonitoringAgent.Data.Interfaces.Entities;
using MonitoringAgent.Data.Interfaces.Managers;

namespace MonitoringAgent.Common.Data.Managers
{
    
    public partial class ManagersProvider
    {
    	public void RegisterManagers(IUnityContainer container)
    	{
    		container.RegisterType<ISiteInfoManager, SiteInfoManager>(new PerResolveLifetimeManager());
    		container.RegisterType<ISiteInfoCheckResultManager, SiteInfoCheckResultManager>(new PerResolveLifetimeManager());
    		container.RegisterType<IStateManager, StateManager>(new PerResolveLifetimeManager());
    		container.RegisterType<IWcfServiceInfoManager, WcfServiceInfoManager>(new PerResolveLifetimeManager());
    		container.RegisterType<IWcfServiceInfoCheckResultManager, WcfServiceInfoCheckResultManager>(new PerResolveLifetimeManager());
    	}
    }
}
