//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MonitoringAgent.Data.Interfaces.Entities;
using MonitoringAgent.Data.Interfaces.Managers;

namespace MonitoringAgent.Common.Data.Managers
{
    
    public partial class SiteInfoManager: BaseManager<SiteInfo>, ISiteInfoManager
    {
    	public SiteInfoManager(DbContextProvider contextProvider) : base(contextProvider)
        {
        }
    }
    
}
