//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MonitoringAgent.Data.Interfaces.Entities;

namespace MonitoringAgent.Data.Interfaces.Managers
{
    
    public partial interface ISiteInfoCheckResultManager: IBaseManager<SiteInfoCheckResult>
    {
    }
    
}
