//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;    
using System.Data.Entity.ModelConfiguration;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.DriverLicenceMasterData;

namespace TuevSued.V1.IT.FE.MasterDataModule.Lib.Data
{
        /// <summary>
        /// Database mapping for <see cref="LegalBasis"/> to table DRL_EXAM_RECOGNITION_TYPE
        /// </summary>
        internal sealed class ExamRecognitionTypeMapping : EntityTypeConfiguration<ExamRecognitionType>
        {
    	    public static readonly ExamRecognitionTypeMapping Instance = new ExamRecognitionTypeMapping();
    	    /// <summary>
            /// Instance constructor
            /// </summary>
            private ExamRecognitionTypeMapping()
            {
                // Primary Key
                this.HasKey(t => t.Id);
    
                // Properties
                this.Property(t => t.Id)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.Name)
                    .IsRequired()
                    .IsUnicode()
                    .HasMaxLength(50);
    
                this.Property(t => t.Description)
                    .IsRequired()
                    .IsUnicode()
                    .HasMaxLength(250);
    
               
    
                this.Property(t => t.CreateDate)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
               
    
                // Table & Column Mappings
                this.ToTable("DRL_EXAM_RECOGNITION_TYPE", "DATA");
                this.Property(t => t.Id).HasColumnName(ExamRecognitionType.Fields.Id);
                this.Property(t => t.Name).HasColumnName(ExamRecognitionType.Fields.Name);
                this.Property(t => t.Description).HasColumnName(ExamRecognitionType.Fields.Description);
                this.Property(t => t.CreateDate).HasColumnName(ExamRecognitionType.Fields.CreateDate);
                this.Property(t => t.ChangeDate).HasColumnName(ExamRecognitionType.Fields.ChangeDate);
                this.Property(t => t.OwnerOrgId).HasColumnName(ExamRecognitionType.Fields.OwnerOrgId);
                this.Property(t => t.VisibilityOrgId).HasColumnName(ExamRecognitionType.Fields.VisibilityOrgId);
                this.Property(t => t.CreateEmployeeId).HasColumnName(ExamRecognitionType.Fields.CreateEmployeeId);
                this.Property(t => t.ChangeEmployeeId).HasColumnName(ExamRecognitionType.Fields.ChangeEmployeeId);
                this.Property(t => t.FromDate).HasColumnName(ExamRecognitionType.Fields.FromDate);
                this.Property(t => t.ToDate).HasColumnName(ExamRecognitionType.Fields.ToDate);
                this.Property(t => t.DeleteDate).HasColumnName(ExamRecognitionType.Fields.DeleteDate);
            }
        }
}
