//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.DriverLicenceMasterData;

namespace TuevSued.V1.IT.FE.MasterDataModule.Lib.Data
{
    /// <summary>
    /// Database mapping for <see cref="ExamClassRequiredClass"/> to table DRL_EXAM_CLASS_REQUIRED_CLASS_RSP
    /// </summary>
    internal sealed class ExamClassRequiredClassMapping : EntityTypeConfiguration<ExamClassRequiredClass>
    {
        public static readonly ExamClassRequiredClassMapping Instance = new ExamClassRequiredClassMapping();
        /// <summary>
        /// Instance constructor
        /// </summary>
        private ExamClassRequiredClassMapping()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            this.Property(t => t.CreateDate)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            // Table & Column Mappings
            this.ToTable("DRL_EXAM_CLASS_REQUIRED_CLASS_RSP", "DATA");
            this.Property(t => t.Id).HasColumnName(ExamClassRequiredClass.Fields.Id);
            this.Property(t => t.ExamClassId).HasColumnName(ExamClassRequiredClass.Fields.ExamClassId);
            this.Property(t => t.ExamClassIdRequired).HasColumnName(ExamClassRequiredClass.Fields.ExamClassIdRequired);
            this.Property(t => t.CreateDate).HasColumnName(ExamClassRequiredClass.Fields.CreateDate);
            this.Property(t => t.ChangeDate).HasColumnName(ExamClassRequiredClass.Fields.ChangeDate);
            this.Property(t => t.OwnerOrgId).HasColumnName(ExamClassRequiredClass.Fields.OwnerOrgId);
            this.Property(t => t.VisibilityOrgId).HasColumnName(ExamClassRequiredClass.Fields.VisibilityOrgId);
            this.Property(t => t.CreateEmployeeId).HasColumnName(ExamClassRequiredClass.Fields.CreateEmployeeId);
            this.Property(t => t.ChangeEmployeeId).HasColumnName(ExamClassRequiredClass.Fields.ChangeEmployeeId);
            this.Property(t => t.FromDate).HasColumnName(ExamClassRequiredClass.Fields.FromDate);
            this.Property(t => t.ToDate).HasColumnName(ExamClassRequiredClass.Fields.ToDate);
            this.Property(t => t.DeleteDate).HasColumnName(ExamClassRequiredClass.Fields.DeleteDate);

            // Relationships
            this.HasRequired(t => t.ExamClass)
                .WithMany(t => t.ExamClassRequiredClasses)
                .HasForeignKey(d => d.ExamClassId);
            this.HasRequired(t => t.ExamCLASS1)
                .WithMany(t => t.ExamClassRequiredClassRSP1)
                .HasForeignKey(d => d.ExamClassIdRequired);


        }
    }
}
