//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;    
using System.Data.Entity.ModelConfiguration;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.DriverLicenceMasterData;

namespace TuevSued.V1.IT.FE.MasterDataModule.Lib.Data
{
        /// <summary>
        /// Database mapping for <see cref="Language"/> to table DRL_LANGUAGE
        /// </summary>
        internal sealed class LanguageMapping : EntityTypeConfiguration<Language>
        {
    	    public static readonly LanguageMapping Instance = new LanguageMapping();
    	    /// <summary>
            /// Instance constructor
            /// </summary>
            private LanguageMapping()
            {
                // Primary Key
                this.HasKey(t => t.Id);
    
                // Properties
                this.Property(t => t.Id)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.OldAbbr)
                    .IsRequired()
                    .IsUnicode()
                    .HasMaxLength(10);
    
                this.Property(t => t.CreateDate)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.RowVersion)
                    .IsRequired()
                    .IsFixedLength()
                    .HasMaxLength(8)
                    .IsRowVersion();
    
                // Table & Column Mappings
                this.ToTable("DRL_LANGUAGE", "DATA");
                this.Property(t => t.Id).HasColumnName(Language.Fields.Id);
                this.Property(t => t.SysLanguageId).HasColumnName(Language.Fields.SysLanguageId);
                this.Property(t => t.OldAbbr).HasColumnName(Language.Fields.OldAbbr);
                this.Property(t => t.CreateDate).HasColumnName(Language.Fields.CreateDate);
                this.Property(t => t.ChangeDate).HasColumnName(Language.Fields.ChangeDate);
                this.Property(t => t.OwnerOrgId).HasColumnName(Language.Fields.OwnerOrgId);
                this.Property(t => t.VisibilityOrgId).HasColumnName(Language.Fields.VisibilityOrgId);
                this.Property(t => t.CreateEmployeeId).HasColumnName(Language.Fields.CreateEmployeeId);
                this.Property(t => t.ChangeEmployeeId).HasColumnName(Language.Fields.ChangeEmployeeId);
                this.Property(t => t.FromDate).HasColumnName(Language.Fields.FromDate);
                this.Property(t => t.ToDate).HasColumnName(Language.Fields.ToDate);
                this.Property(t => t.RowVersion).HasColumnName(Language.Fields.RowVersion);
                this.Property(t => t.DeleteDate).HasColumnName(Language.Fields.DeleteDate);
    
                // Relationships
                this.HasRequired(t => t.SysLanguage)
                    .WithMany(t => t.Languages)
                    .HasForeignKey(d => d.SysLanguageId);
    
            }
        }
}
