//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using TuevSued.V1.IT.CoreBase.Entities.MasterDataModule.DriverLicenceMasterData;
namespace TuevSued.V1.IT.FE.MasterDataModule.Lib.Data
{
        /// <summary>
        /// Database mapping for <see cref="ReturnReason"/> to table DRL_RETURN_REASON
        /// </summary>
        internal sealed class ReturnReasonMapping : EntityTypeConfiguration<ReturnReason>
        {
    	    public static readonly ReturnReasonMapping Instance = new ReturnReasonMapping();
    	    /// <summary>
            /// Instance constructor
            /// </summary>
            private ReturnReasonMapping()
            {
                // Primary Key
                this.HasKey(t => t.Id);
    
                // Properties
                this.Property(t => t.Id)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                this.Property(t => t.Name)
                    .IsRequired()
                    .IsUnicode()
                    .HasMaxLength(50);
    
                this.Property(t => t.Description)
                    .IsRequired()
                    .IsUnicode()
                    .HasMaxLength(250);
    
                this.Property(t => t.Text1)
                    .IsUnicode()
                    .HasMaxLength(200);
    
                this.Property(t => t.Text2)
                    .IsUnicode()
                    .HasMaxLength(200);
    
                this.Property(t => t.CreateDate)
                    .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                // Table & Column Mappings
                this.ToTable("DRL_RETURN_REASON", "DATA");
                this.Property(t => t.Id).HasColumnName(ReturnReason.Fields.Id);
                this.Property(t => t.Name).HasColumnName(ReturnReason.Fields.Name);
                this.Property(t => t.Description).HasColumnName(ReturnReason.Fields.Description);
                this.Property(t => t.Text1).HasColumnName(ReturnReason.Fields.Text1);
                this.Property(t => t.Text2).HasColumnName(ReturnReason.Fields.Text2);
                this.Property(t => t.CreateDate).HasColumnName(ReturnReason.Fields.CreateDate);
                this.Property(t => t.ChangeDate).HasColumnName(ReturnReason.Fields.ChangeDate);
                this.Property(t => t.OwnerOrgId).HasColumnName(ReturnReason.Fields.OwnerOrgId);
                this.Property(t => t.VisibilityOrgId).HasColumnName(ReturnReason.Fields.VisibilityOrgId);
                this.Property(t => t.CreateEmployeeId).HasColumnName(ReturnReason.Fields.CreateEmployeeId);
                this.Property(t => t.ChangeEmployeeId).HasColumnName(ReturnReason.Fields.ChangeEmployeeId);
                this.Property(t => t.FromDate).HasColumnName(ReturnReason.Fields.FromDate);
                this.Property(t => t.ToDate).HasColumnName(ReturnReason.Fields.ToDate);
                this.Property(t => t.DeleteDate).HasColumnName(ReturnReason.Fields.DeleteDate);
            }
        }
}
