USE SettingsData;
IF (OBJECT_ID('SERVICE_UPDATE_TABLE_DESCRIPTIONS_T', 'TR') IS NOT NULL)
  DROP TRIGGER [SERVICE_UPDATE_TABLE_DESCRIPTIONS_T] ON DATABASE;
IF (OBJECT_ID('SERVICE.UPDATE_TABLE_DESCRIPTIONS', 'P') IS NOT NULL)
  DROP PROCEDURE [SERVICE].[UPDATE_TABLE_DESCRIPTIONS];
