set identity_insert [dbo].MASTER_DATA_PERMISSION ON;

DELETE FROM [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
WHERE (SELECT TOP(1) ID FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'LogTypeInfo') = MASTER_DATA_PERMISSION_ID

DELETE FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'LogTypeInfo';

INSERT INTO [dbo].[MASTER_DATA_PERMISSION] (ID, SYSTEM_NAME, NAME, CREATE_DATE, CHANGE_DATE, FROM_DATE, TO_DATE)
VALUES(25, 'SettingsData', 'LogTypeInfo', GetDate(), GetDate(), '2015.04.10', '2070.12.31');

INSERT INTO [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
(MASTER_DATA_ROLE_ID, MASTER_DATA_PERMISSION_ID, CREATE_DATE, CHANGE_DATE,  FROM_DATE, TO_DATE
)
(SELECT 1, ID, GetDate(), GetDate(), '2015.04.10', '2070.12.31'
FROM [dbo].[MASTER_DATA_PERMISSION]
WHERE NAME = 'LogTypeInfo');

set identity_insert MASTER_DATA_PERMISSION OFF;