USE [SettingsData]
GO

IF EXISTS (
	SELECT OBJECT_ID
	FROM SYS.VIEWS 
	WHERE NAME = N'GET_JOBS_STATUS')
BEGIN
  DROP VIEW [dbo].[GET_JOBS_STATUS];  
END;


DECLARE @query varchar(max);

set @query = 'CREATE VIEW [dbo].[GET_JOBS_STATUS] 
AS
SELECT 
	 res.ID
	,res.CHECK_STATUS
	,res.CHECK_DATE
	,res.LAST_RUN_TIME
	,inf.[NAME]
	,inf.JOB_NAME
	,res.DELETE_DATE
	,res.CREATE_DATE
	,res.CHANGE_DATE
FROM 
	[dbo].[MASTER_DATA_JOB_CHECK_RESULTS] res INNER JOIN
	[dbo].[MASTER_DATA_JOB_INFO] inf ON res.[MASTER_DATA_JOB_INFO_ID] = inf.ID
WHERE res.DELETE_DATE IS NULL
AND inf.DELETE_DATE IS NULL';

EXEC (@query);

IF EXISTS (
	SELECT OBJECT_ID
	FROM SYS.VIEWS 
	WHERE NAME = N'GET_WCF_SERVICES_STATUS')
  DROP VIEW [dbo].[GET_WCF_SERVICES_STATUS];  


set @query = 'CREATE VIEW [dbo].[GET_WCF_SERVICES_STATUS] 
AS
SELECT 
	res.ID
	,res.CHECK_STATUS
	,res.CHECK_DATE
	,res.[MESSAGE]
	,res.ATTEMPT
	,inf.[NAME]
	,inf.WSDL_PATH
	,res.DELETE_DATE
	,res.CREATE_DATE
	,res.CHANGE_DATE
FROM 
	[dbo].[MASTER_DATA_WCF_CHECK_RESULTS] res INNER JOIN
	[dbo].[MASTER_DATA_WCF_INFO] inf ON res.[MASTER_DATA_WCF_INFO_ID] = inf.ID'


EXEC (@query);

