USE [SettingsData]
GO

IF EXISTS (
	SELECT OBJECT_ID
	FROM SYS.VIEWS 
	WHERE NAME = N'GET_WIN_SERVICES_STATUS')
BEGIN
  DROP VIEW [dbo].[GET_WIN_SERVICES_STATUS];  
END;


DECLARE @query varchar(max);

set @query = 'CREATE VIEW [dbo].[GET_WIN_SERVICES_STATUS] 
AS
SELECT 
	 res.ID
	,res.CHECK_STATUS
	,res.CHECK_DATE
	,res.MESSAGE
	,res.ATTEMPT
	,inf.[NAME]
	,inf.MACHINE_NAME
	,res.DELETE_DATE
	,res.CREATE_DATE
	,res.CHANGE_DATE
FROM 
	[dbo].[MASTER_DATA_WINDOWS_SERVICE_CHECK_RESULTS] res INNER JOIN
	[dbo].[MASTER_DATA_WINDOWS_SERVICE_INFO] inf ON res.[MASTER_DATA_WINDOWS_SERVICE_INFO_ID] = inf.ID
WHERE res.DELETE_DATE IS NULL
AND inf.DELETE_DATE IS NULL';

EXEC (@query);

IF EXISTS (
	SELECT OBJECT_ID
	FROM SYS.VIEWS 
	WHERE NAME = N'GET_SITES_STATUS')
  DROP VIEW [dbo].[GET_SITES_STATUS];  


set @query = 'CREATE VIEW [dbo].[GET_SITES_STATUS] 
AS
SELECT 
	res.ID
	,res.CHECK_STATUS
	,res.CHECK_DATE
	,res.[MESSAGE]
	,res.ATTEMPT
	,inf.[NAME]
	,inf.SITE_PATH
	,res.DELETE_DATE
	,res.CREATE_DATE
	,res.CHANGE_DATE
FROM 
	[dbo].[MASTER_DATA_SITE_CHECK_RESULTS] res INNER JOIN
	[dbo].[MASTER_DATA_SITE_INFO] inf ON res.[MASTER_DATA_SITE_INFO_ID] = inf.ID'


EXEC (@query);

