IF (OBJECT_ID('SITE_INFOS_WITH_LAST_RESULT', 'V') IS NOT NULL)
  DROP VIEW [dbo].[SITE_INFOS_WITH_LAST_RESULT];
GO  
IF (OBJECT_ID('WCF_INFOS_WITH_LAST_RESULT', 'V') IS NOT NULL)
  DROP VIEW [dbo].[WCF_INFOS_WITH_LAST_RESULT];
GO  
IF (OBJECT_ID('WINSERVICE_INFOS_WITH_LAST_RESULT', 'V') IS NOT NULL)
  DROP VIEW [dbo].[WINSERVICE_INFOS_WITH_LAST_RESULT];
GO  
IF (OBJECT_ID('JOBS_INFOS_WITH_LAST_RESULT', 'V') IS NOT NULL)
  DROP VIEW [dbo].[JOBS_INFOS_WITH_LAST_RESULT];
GO  

CREATE VIEW [dbo].[SITE_INFOS_WITH_LAST_RESULT]
AS
SELECT
info.ID,
info.[NAME],
(SELECT TOP(1) CHECK_STATUS FROM MASTER_DATA_SITE_CHECK_RESULTS WHERE MASTER_DATA_SITE_INFO_ID = info.ID ORDER BY CHECK_DATE DESC) AS LAST_RESULT
FROM MASTER_DATA_SITE_INFO info WHERE DELETE_DATE IS NULL
GO
CREATE VIEW [dbo].[WCF_INFOS_WITH_LAST_RESULT]
AS
SELECT
info.ID,
info.[NAME],
(SELECT TOP(1) CHECK_STATUS FROM dbo.MASTER_DATA_WCF_CHECK_RESULTS WHERE MASTER_DATA_WCF_INFO_ID = info.ID ORDER BY CHECK_DATE DESC) AS LAST_RESULT
FROM dbo.MASTER_DATA_WCF_INFO info WHERE DELETE_DATE IS NULL
GO
CREATE VIEW [dbo].[WINSERVICE_INFOS_WITH_LAST_RESULT]
AS
SELECT
info.ID,
info.[NAME],
(SELECT TOP(1) CHECK_STATUS FROM dbo.MASTER_DATA_WINDOWS_SERVICE_CHECK_RESULTS WHERE MASTER_DATA_WINDOWS_SERVICE_INFO_ID = info.ID ORDER BY CHECK_DATE DESC) AS LAST_RESULT
FROM dbo.MASTER_DATA_WINDOWS_SERVICE_INFO info WHERE DELETE_DATE IS NULL
GO
CREATE VIEW [dbo].[JOBS_INFOS_WITH_LAST_RESULT]
AS
SELECT
info.ID,
info.[NAME],
(SELECT TOP(1) CHECK_STATUS FROM dbo.MASTER_DATA_JOB_CHECK_RESULTS WHERE MASTER_DATA_JOB_INFO_ID = info.ID ORDER BY CHECK_DATE DESC) AS LAST_RESULT
FROM dbo.MASTER_DATA_JOB_INFO info WHERE DELETE_DATE IS NULL
GO