set identity_insert [dbo].MASTER_DATA_PERMISSION ON;

--- GetWinServicesStatus
DELETE FROM [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
WHERE (SELECT TOP(1) ID FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetWinServicesStatus') = MASTER_DATA_PERMISSION_ID

DELETE FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetWinServicesStatus';

INSERT INTO [dbo].[MASTER_DATA_PERMISSION] (ID, SYSTEM_NAME, NAME, CREATE_DATE, CHANGE_DATE, FROM_DATE, TO_DATE)
VALUES(27, 'SettingsData', 'GetWinServicesStatus', GetDate(), GetDate(), '2015.04.10', '2070.12.31');

INSERT INTO [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
(MASTER_DATA_ROLE_ID, MASTER_DATA_PERMISSION_ID, CREATE_DATE, CHANGE_DATE,  FROM_DATE, TO_DATE
)
(SELECT 1, ID, GetDate(), GetDate(), '2015.04.10', '2070.12.31'
FROM [dbo].[MASTER_DATA_PERMISSION]
WHERE NAME = 'GetWinServicesStatus');


--- GetSitesStatus
DELETE FROM [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
WHERE (SELECT TOP(1) ID FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetSitesStatus') = MASTER_DATA_PERMISSION_ID

DELETE FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetSitesStatus';

INSERT INTO [dbo].[MASTER_DATA_PERMISSION] (ID, SYSTEM_NAME, NAME, CREATE_DATE, CHANGE_DATE, FROM_DATE, TO_DATE)
VALUES(28, 'SettingsData', 'GetSitesStatus', GetDate(), GetDate(), '2015.04.10', '2070.12.31');

INSERT INTO [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
(MASTER_DATA_ROLE_ID, MASTER_DATA_PERMISSION_ID, CREATE_DATE, CHANGE_DATE,  FROM_DATE, TO_DATE
)
(SELECT 1, ID, GetDate(), GetDate(), '2015.04.10', '2070.12.31'
FROM [dbo].[MASTER_DATA_PERMISSION]
WHERE NAME = 'GetSitesStatus');


--- GetJobsStatus
DELETE FROM [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
WHERE (SELECT TOP(1) ID FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetJobsStatus') = MASTER_DATA_PERMISSION_ID

DELETE FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetJobsStatus';

INSERT INTO [dbo].[MASTER_DATA_PERMISSION] (ID, SYSTEM_NAME, NAME, CREATE_DATE, CHANGE_DATE, FROM_DATE, TO_DATE)
VALUES(29, 'SettingsData', 'GetJobsStatus', GetDate(), GetDate(), '2015.04.10', '2070.12.31');

INSERT INTO [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
(MASTER_DATA_ROLE_ID, MASTER_DATA_PERMISSION_ID, CREATE_DATE, CHANGE_DATE,  FROM_DATE, TO_DATE
)
(SELECT 1, ID, GetDate(), GetDate(), '2015.04.10', '2070.12.31'
FROM [dbo].[MASTER_DATA_PERMISSION]
WHERE NAME = 'GetJobsStatus');

---- GetWcfServicesStatus

DELETE FROM [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
WHERE (SELECT TOP(1) ID FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetWcfServicesStatus') = MASTER_DATA_PERMISSION_ID

DELETE FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetWcfServicesStatus';

INSERT INTO [dbo].[MASTER_DATA_PERMISSION] (ID, SYSTEM_NAME, NAME, CREATE_DATE, CHANGE_DATE, FROM_DATE, TO_DATE)
VALUES(30, 'SettingsData', 'GetWcfServicesStatus', GetDate(), GetDate(), '2015.04.10', '2070.12.31');

INSERT INTO [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
(MASTER_DATA_ROLE_ID, MASTER_DATA_PERMISSION_ID, CREATE_DATE, CHANGE_DATE,  FROM_DATE, TO_DATE
)
(SELECT 1, ID, GetDate(), GetDate(), '2015.04.10', '2070.12.31'
FROM [dbo].[MASTER_DATA_PERMISSION]
WHERE NAME = 'GetWcfServicesStatus');


---- GetApplicationLogs

DELETE FROM [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
WHERE (SELECT TOP(1) ID FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetApplicationLogs') = MASTER_DATA_PERMISSION_ID

DELETE FROM [dbo].[MASTER_DATA_PERMISSION] WHERE SYSTEM_NAME = 'SettingsData' AND [NAME] = 'GetApplicationLogs';

INSERT INTO [dbo].[MASTER_DATA_PERMISSION] (ID, SYSTEM_NAME, NAME, CREATE_DATE, CHANGE_DATE, FROM_DATE, TO_DATE)
VALUES(9, 'SettingsData', 'GetApplicationLogs', GetDate(), GetDate(), '2015.04.10', '2070.12.31');

INSERT INTO [dbo].[MASTER_DATA_ROLE_PERMISSION_RSP]
(MASTER_DATA_ROLE_ID, MASTER_DATA_PERMISSION_ID, CREATE_DATE, CHANGE_DATE,  FROM_DATE, TO_DATE
)
(SELECT 1, ID, GetDate(), GetDate(), '2015.04.10', '2070.12.31'
FROM [dbo].[MASTER_DATA_PERMISSION]
WHERE NAME = 'GetApplicationLogs');


set identity_insert MASTER_DATA_PERMISSION OFF;