/****** Object: Table [dbo].[LOG_TYPE_INFO]   Script Date: 21.04.2015 0:28:16 ******/
USE [SettingsData];

ALTER TABLE [dbo].[APPLICATION_LOGS] 
  DROP CONSTRAINT [FK_LOG_TYPE_INFO_APPLICATION_LOGS];
GO
ALTER TABLE [dbo].[MASTER_DATA_JOB_INFO] 
  DROP CONSTRAINT [FK_LOG_TYPE_INFO_MASTER_DATA_JOB_INFO];

GO
ALTER TABLE [dbo].[MASTER_DATA_SITE_INFO] 
  DROP CONSTRAINT [FK_LOG_TYPE_INFO_MASTER_DATA_SITE_INFO];

GO
ALTER TABLE [dbo].[MASTER_DATA_WCF_INFO] 
  DROP CONSTRAINT [FK_LOG_TYPE_INFO_MASTER_DATA_WCF_INFO];
  
GO
ALTER TABLE [dbo].[MASTER_DATA_WINDOWS_SERVICE_INFO] 
  DROP CONSTRAINT [FK_LOG_TYPE_INFO_MASTER_DATA_WINDOWS_SERVICE_INFO]; 

GO
IF (OBJECT_ID('dbo.LOG_TYPE_INFO', 'U') IS NOT NULL)
  DROP TABLE [dbo].[LOG_TYPE_INFO];

GO
CREATE TABLE [dbo].[LOG_TYPE_INFO] (
[ID] int IDENTITY(0, 1) NOT NULL,
[CREATE_DATE] datetime2(2) NOT NULL DEFAULT (getdate()),
[DELETE_DATE] datetime2(2) NULL,
[CHANGE_DATE] datetime2(2) NOT NULL DEFAULT (getdate()),
[FROM_DATE] datetime2(2) NOT NULL DEFAULT (getdate()),
[TO_DATE] datetime2(2) NOT NULL DEFAULT (dateadd(year,(1),getdate())),
[FILE_NAME] varchar(250) NOT NULL,
[FILE_PATTERN] varchar(250) NOT NULL,
[FILE_PATH] varchar(MAX) NOT NULL,
[LAST_READ_DATE] datetime2(7) NULL,
[MESSAGE_PATTERN] nvarchar(MAX) NULL,
[LAST_READ_POSITION] bigint NULL,
[START_MESSAGE_PATTERN] nvarchar(MAX) NULL,
[CHECKING_TIMEOUT] int NULL,
[LAST_PROCESSED_FILE] nvarchar(MAX) NULL,
CONSTRAINT [PK_LOG_TYPE_INFO]
PRIMARY KEY CLUSTERED ([ID] ASC)
)
GO
ALTER TABLE [dbo].[LOG_TYPE_INFO] SET (LOCK_ESCALATION = TABLE);
GO
EXEC [sys].[sp_addextendedproperty] @name = N'MS_Description', @value = N'DE:Von Datum  EN:  Date from', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'LOG_TYPE_INFO', @level2type = N'COLUMN', @level2name = N'FROM_DATE';
GO
EXEC [sys].[sp_addextendedproperty] @name = N'MS_Description', @value = N'DE:Bis Datum  EN:  Date to', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'LOG_TYPE_INFO', @level2type = N'COLUMN', @level2name = N'TO_DATE';
GO
ALTER TABLE dbo.MASTER_DATA_JOB_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_JOB_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE dbo.MASTER_DATA_SITE_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_SITE_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE dbo.MASTER_DATA_WCF_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_WCF_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE dbo.MASTER_DATA_WINDOWS_SERVICE_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_WINDOWS_SERVICE_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

DELETE FROM [dbo].[APPLICATION_LOGS]
GO

ALTER TABLE dbo.APPLICATION_LOGS ADD CONSTRAINT
	FK_LOG_TYPE_INFO_APPLICATION_LOGS FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
INSERT INTO [dbo].[LOG_TYPE_INFO] ([FILE_NAME], [FILE_PATTERN], [FILE_PATH], [MESSAGE_PATTERN], [START_MESSAGE_PATTERN], [CHECKING_TIMEOUT])
VALUES ('ClientMain', 'ClientMain*.*', 'D:\Test\Logs', N'(?<messageType>\w{4,7})\s?;(?<time>.+);(?<message>.*)', N'^\w{4,7}\s?;.+', 10000)
INSERT INTO [dbo].[LOG_TYPE_INFO] ([FILE_NAME], [FILE_PATTERN], [FILE_PATH], [MESSAGE_PATTERN], [START_MESSAGE_PATTERN], [CHECKING_TIMEOUT])
VALUES ('WebMain', 'WebMain*.*', 'D:\Test\Logs', N'(?<messageType>\w{4,7})\s?;(?<time>.+);(?<message>.*)', N'^\w{4,7}\s?;.+', 10000)
INSERT INTO [dbo].[LOG_TYPE_INFO] ([FILE_NAME], [FILE_PATTERN], [FILE_PATH], [MESSAGE_PATTERN], [START_MESSAGE_PATTERN], [CHECKING_TIMEOUT])
VALUES ('FeServiceMain', 'FeServiceMain*.*', 'D:\Test\Logs', N'===\s(?<messageType>.+)\t(?<time>.+)\|(?<message>.+)', N'=== .+', 10000)
INSERT INTO [dbo].[LOG_TYPE_INFO] ([FILE_NAME], [FILE_PATTERN], [FILE_PATH], [MESSAGE_PATTERN], [START_MESSAGE_PATTERN], [CHECKING_TIMEOUT])
VALUES ('FEWebMain', 'FEWebMain*.*', 'D:\Test\Logs', N'===\s(?<messageType>.+)\t(?<time>.+)\|(?<message>.+)', N'=== .+', 10000)



