/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/

CREATE TABLE dbo.LOG_TYPE_INFO
	(
	ID int NOT NULL identity(0, 1) primary key ,
	CREATE_DATE datetime2(2) NOT NULL,
	DELETE_DATE datetime2(2) NULL,
	CHANGE_DATE datetime2(2) NOT NULL,
	FROM_DATE datetime2(2) NOT NULL,
	TO_DATE datetime2(2) NOT NULL,
	FILE_NAME varchar(250) NOT NULL,
	FILE_PATTERN varchar(250) NOT NULL,
	FILE_PATH varchar(max) NOT NULL
	)  ON [PRIMARY]
GO
DECLARE @v sql_variant 
SET @v = N'DE:Von Datum  EN:  Date from'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'LOG_TYPE_INFO', N'COLUMN', N'FROM_DATE'
GO
DECLARE @v sql_variant 
SET @v = N'DE:Bis Datum  EN:  Date to'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'LOG_TYPE_INFO', N'COLUMN', N'TO_DATE'
GO
ALTER TABLE dbo.LOG_TYPE_INFO ADD CONSTRAINT
	DF_LOG_TYPE_INFO_CREATE_DATE DEFAULT (getdate()) FOR CREATE_DATE
GO
ALTER TABLE dbo.LOG_TYPE_INFO ADD CONSTRAINT
	DF_LOG_TYPE_INFO_CHANGE_DATE DEFAULT (getdate()) FOR CHANGE_DATE
GO
ALTER TABLE dbo.LOG_TYPE_INFO ADD CONSTRAINT
	DF_LOG_TYPE_INFO_FROM_DATE DEFAULT (getdate()) FOR FROM_DATE
GO
ALTER TABLE dbo.LOG_TYPE_INFO ADD CONSTRAINT
	DF_LOG_TYPE_INFO_TO_DATE DEFAULT (dateadd(year,(1),getdate())) FOR TO_DATE
GO

ALTER TABLE [dbo].[MASTER_DATA_JOB_INFO]
ADD LOG_TYPE_INFO_ID int NULL
GO


ALTER TABLE dbo.MASTER_DATA_JOB_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_JOB_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE [dbo].[MASTER_DATA_SITE_INFO]
ADD LOG_TYPE_INFO_ID int NULL
GO


ALTER TABLE dbo.MASTER_DATA_SITE_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_SITE_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE [dbo].[MASTER_DATA_WCF_INFO]
ADD LOG_TYPE_INFO_ID int NULL
GO


ALTER TABLE dbo.MASTER_DATA_WCF_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_WCF_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE [dbo].[MASTER_DATA_WINDOWS_SERVICE_INFO]
ADD LOG_TYPE_INFO_ID int NULL
GO


ALTER TABLE dbo.MASTER_DATA_WINDOWS_SERVICE_INFO ADD CONSTRAINT
	FK_LOG_TYPE_INFO_MASTER_DATA_WINDOWS_SERVICE_INFO FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

DELETE FROM [dbo].[APPLICATION_LOGS]
GO

ALTER TABLE [dbo].[APPLICATION_LOGS]
DROP COLUMN LOG_TYPE
GO

ALTER TABLE [dbo].[APPLICATION_LOGS]
ADD LOG_TYPE_INFO_ID int NOT NULL
GO


ALTER TABLE dbo.APPLICATION_LOGS ADD CONSTRAINT
	FK_LOG_TYPE_INFO_APPLICATION_LOGS FOREIGN KEY
	(
	LOG_TYPE_INFO_ID
	) REFERENCES dbo.LOG_TYPE_INFO
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

