CREATE VIEW dbo.[GET_WCF_SERVICES_STATUS] 
AS
SELECT 
	res.ID
	,res.CHECK_STATUS
	,res.CHECK_DATE
	,res.[MESSAGE]
	,res.ATTEMPT
	,inf.[NAME]
	,inf.WSDL_PATH
FROM 
	[dbo].[MASTER_DATA_WCF_CHECK_RESULTS] res INNER JOIN
	[dbo].[MASTER_DATA_WCF_INFO] inf ON res.[MASTER_DATA_WCF_INFO_ID] = inf.ID
GO


