USE [SettingsData];

IF EXISTS (SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = N'MASTER_DATA_MONITORABLE_INFO_MASTER_DATA_NOTIFICATIONS_RSP')
  DROP TABLE [dbo].[MASTER_DATA_MONITORABLE_INFO_MASTER_DATA_NOTIFICATIONS_RSP];  
  
IF EXISTS (SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = N'MASTER_DATA_NOTIFICATIONS_MASTER_DATA_SUBSCRIBERS_RSP')
  DROP TABLE [dbo].[MASTER_DATA_NOTIFICATIONS_MASTER_DATA_SUBSCRIBERS_RSP];  
  
IF EXISTS (SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = N'MASTER_DATA_NOTIFICATIONS')
  DROP TABLE [dbo].[MASTER_DATA_NOTIFICATIONS];    
  
IF EXISTS (SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = N'MASTER_DATA_SUBSCRIBERS')
  DROP TABLE [dbo].[MASTER_DATA_SUBSCRIBERS];
    
CREATE TABLE [dbo].[MASTER_DATA_SUBSCRIBERS] (
[ID] int IDENTITY(1, 1) NOT NULL,
[EMAIL] nvarchar(MAX) NOT NULL,
[CREATE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[CHANGE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[DELETE_DATE] datetime2(2) NULL,
CONSTRAINT PK_MASTER_DATA_SUBSCRIBER_ID PRIMARY KEY CLUSTERED ([ID] )
);

CREATE TABLE [dbo].[MASTER_DATA_NOTIFICATIONS](
[ID] int IDENTITY(1, 1) NOT NULL,
[NOTIFICATION_TYPE] int NOT NULL,
[IS_ALERT_ON] bit NOT NULL DEFAULT 1,
[ALERT_CHECK_STATUS] int NOT NULL DEFAULT 0,
[ALERT_ATTEMPT_COUNT] int NOT NULL DEFAULT 1,
[MESSAGE]nvarchar(max),
[CREATE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[CHANGE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[DELETE_DATE] datetime2(2) NULL,
CONSTRAINT PK_MASTER_DATA_NOTIFICATIONS PRIMARY KEY CLUSTERED ([ID] )
);

CREATE TABLE [dbo].[MASTER_DATA_MONITORABLE_INFO_MASTER_DATA_NOTIFICATIONS_RSP](
[ID] int IDENTITY(1, 1) NOT NULL,
[MONITORABLE_INFO_TYPE] int NOT NULL,
[MONITORABLE_INFO_ID] int NOT NULL,
[MASTER_DATA_NOTIFICATIONS_ID] int NOT NULL,
[CREATE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[CHANGE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[DELETE_DATE] datetime2(2) NULL,
CONSTRAINT PK_MASTER_DATA_MONITORABLE_INFO_MASTER_DATA_NOTIFICATIONS_RSP PRIMARY KEY CLUSTERED ([ID]),
CONSTRAINT FK_MASTER_DATA_MONITORABLE_INFO_MASTER_DATA_NOTIFICATIONS_RSP_MASTER_DATA_NOTIFICATIONS_ID FOREIGN KEY ([MASTER_DATA_NOTIFICATIONS_ID]) REFERENCES [dbo].[MASTER_DATA_NOTIFICATIONS]([ID])
);

CREATE TABLE [dbo].[MASTER_DATA_NOTIFICATIONS_MASTER_DATA_SUBSCRIBERS_RSP](
[ID] int IDENTITY(1, 1) NOT NULL,
[MASTER_DATA_NOTIFICATIONS_ID] int NOT NULL,
[MASTER_DATA_SUBSCRIBERS_ID] int NOT NULL,
[CREATE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[CHANGE_DATE] datetime2(2) NOT NULL DEFAULT GETDATE(),
[DELETE_DATE] datetime2(2) NULL,
CONSTRAINT PK_MASTER_DATA_NOTIFICATIONS_MASTER_DATA_SUBSCRIBERS_RSP PRIMARY KEY CLUSTERED ([ID]),
CONSTRAINT FK_MASTER_DATA_NOTIFICATIONS_MASTER_DATA_SUBSCRIBERS_RSP_MASTER_DATA_NOTIFICATIONS_ID FOREIGN KEY ([MASTER_DATA_NOTIFICATIONS_ID]) REFERENCES [dbo].[MASTER_DATA_NOTIFICATIONS]([ID]),
CONSTRAINT FK_MASTER_DATA_NOTIFICATIONS_MASTER_DATA_SUBSCRIBERS_RSP_MASTER_DATA_SUBSCRIBERS_ID FOREIGN KEY ([MASTER_DATA_SUBSCRIBERS_ID]) REFERENCES [dbo].[MASTER_DATA_SUBSCRIBERS]([ID])
)


