//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringAgent.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WcfServiceInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string WsdlPath { get; set; }
        public Nullable<short> LastCheckStatus { get; set; }
        public Nullable<System.DateTime> LastCheckDate { get; set; }
        public string Message { get; set; }
    }
}
