//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Practices.Unity;
using MonitoringAgent.Common.Data.Managers;
using MonitoringAgent.Data.Interfaces.Entities;
using MonitoringAgent.Data.Interfaces.Managers;

namespace MonitoringAgent.Configuration
{
    
    public partial class Configuration
    {
    	public void RegisterManagers(IUnityContainer container)
    	{
    		container.RegisterType<IWcfServiceInfoManager, WcfServiceInfoManager>();
    		container.RegisterType<IWcfServiceInfoCheckResultManager, WcfServiceInfoCheckResultManager>();
    	}
    }
}
